_BASE_: "/home/detectron2/configs/Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "output/model_final_TSL_754.pth"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 3
    BATCH_SIZE_PER_IMAGE : 128
    SCORE_THRESH_TEST: 0.5
  SEM_SEG_HEAD:
    NUM_CLASSES: 3

SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.001
  STEPS: (3000, 7000)
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 1000 

DATASETS:
  TRAIN: ('0901spreadthesign_men',)
  TEST: ('0901spreadthesign_men',)

# TEST:
#   EVAL_PERIOD: 200

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 0
